---
- hosts: development
  become: yes
  tasks:
    - name: set the port state for minecraft 25565-25575
      firewalld: permanent=True port={{ port }} state={{ state }}
      vars:
        port: 
          - 25565/tcp
          - 25566/tcp
          - 25567/tcp
          - 25568/tcp
          - 25569/tcp
          - 25570/tcp
        state: 
          - enabled
      notify: reload firewalld
      when: firewalld_result.stdout == "active"

  handlers:
    - name: reload firewalld
      service: name=firewalld state=restarted